/**
 * Catálogo oficial GenTrust — alinhado à lista de produtos (imagem oficial).
 * Preços em BRL (centavos exibidos na interface). Categorias: Peptídeos | Hormônios & CIA | Medicamentos
 */
window.GT_CATALOG_DEFAULTS = [
  {
    id: "gt-p001",
    name: "IPAMORELIN",
    dosage: "5mg",
    price: 401,
    description: "Análogo liberador de GH para protocolos de performance e composição corporal.",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "Eixo GH",
    application: "Orientação especializada",
    limitedStock: false
  },
  {
    id: "gt-p002",
    name: "IPAMORELIN",
    dosage: "10mg",
    price: 401,
    description: "Apresentação de maior dose por frasco para ciclos estendidos.",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "Eixo GH",
    application: "Orientação especializada",
    limitedStock: false
  },
  {
    id: "gt-p003",
    name: "TESAMORELIN",
    dosage: "5mg",
    price: 321,
    description: "Análogo de GHRH com foco em sono, recuperação e eixo GH.",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "GH / sono",
    application: "Protocolos noturnos",
    limitedStock: false
  },
  {
    id: "gt-p004",
    name: "TESAMORELIN",
    dosage: "10mg",
    price: 401,
    description: "Versão de dosagem ampliada conforme lista oficial.",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "GH / sono",
    application: "Protocolos supervisionados",
    limitedStock: false
  },
  {
    id: "gt-p005",
    name: "KPV",
    dosage: "10mg",
    price: 321,
    description: "Tripeptídeo com foco imuno-metabólico e controle inflamatório.",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "Metabolismo",
    application: "Curadoria técnica",
    limitedStock: false
  },
  {
    id: "gt-p006",
    name: "AOD 9604",
    dosage: "2mg",
    price: 268,
    description: "Fragmento associado a lipólise e suporte a recomposição corporal.",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "Lipólise",
    application: "Definição",
    limitedStock: false
  },
  {
    id: "gt-p007",
    name: "BPC-157",
    dosage: "5mg",
    price: 268,
    description: "Peptídeo de suporte a reparo tecidual e recuperação.",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "Reparo",
    application: "Recuperação",
    limitedStock: false
  },
  {
    id: "gt-p008",
    name: "BPC-157",
    dosage: "10mg",
    price: 294,
    description: "Maior volume por frasco para protocolos contínuos.",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "Reparo",
    application: "Ciclos longos",
    limitedStock: false
  },
  {
    id: "gt-p009",
    name: "BPC + TB500",
    dosage: "10mg",
    price: 294,
    description: "Combinação clássica para mobilidade tecidual e recuperação.",
    badge: "Blend",
    category: "Peptídeos",
    benefit: "Recuperação",
    application: "Blend premium",
    images: ["./assets/bpc-tb-10mg.png"],
    limitedStock: true
  },
  {
    id: "gt-p010",
    name: "GLOW (Blend)",
    dosage: "—",
    price: 589,
    description: "Blend exclusivo curadoria GenTrust para vitalidade e protocolos glow.",
    badge: "Blend",
    category: "Peptídeos",
    benefit: "Blend premium",
    application: "Sob consultoria",
    images: ["./assets/glow-70mg.png"],
    limitedStock: true
  },
  {
    id: "gt-p011",
    name: "KLOW (Blend)",
    dosage: "—",
    price: 615,
    description: "Blend premium conforme catálogo oficial GenTrust.",
    badge: "Blend",
    category: "Peptídeos",
    benefit: "Blend premium",
    application: "Sob consultoria",
    images: ["./assets/klow-80mg.png"],
    limitedStock: true
  },
  {
    id: "gt-p012",
    name: "GHK-CU",
    dosage: "50mg",
    price: 428,
    description: "Peptídeo de cobre para matriz extracelular e suporte estético.",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "Pele / colágeno",
    application: "Antiaging",
    limitedStock: false
  },
  {
    id: "gt-p013",
    name: "GHK-CU",
    dosage: "100mg",
    price: 589,
    description: "Apresentação de maior volume para protocolos intensivos.",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "Pele / colágeno",
    application: "Estética avançada",
    limitedStock: false
  },
  {
    id: "gt-p014",
    name: "NAD+",
    dosage: "500mg",
    price: 803,
    description: "Coenzima para energia celular e protocolos de longevidade (apresentação bulk).",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "Energia celular",
    application: "Longevidade",
    images: ["./assets/nad-500mg.png"],
    limitedStock: true
  },
  {
    id: "gt-p015",
    name: "SLU-PP 332",
    dosage: "10mg",
    price: 348,
    description: "Modulador metabólico de alta exigência.",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "Metabolismo",
    application: "Cutting técnico",
    limitedStock: false
  },
  {
    id: "gt-p016",
    name: "SLU-PP-332",
    dosage: "5mg",
    price: 305,
    description: "Mesma linha SLU com grafia alternativa do rótulo (conforme lista).",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "Metabolismo",
    application: "Curadoria GT",
    limitedStock: false
  },
  {
    id: "gt-p017",
    name: "SELANK",
    dosage: "5mg",
    price: 268,
    description: "Neuromodulador com foco em calma, foco e equilíbrio emocional.",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "Calma / foco",
    application: "Performance mental",
    limitedStock: false
  },
  {
    id: "gt-p018",
    name: "MELANOTAN2",
    dosage: "10mg",
    price: 268,
    description: "Peptídeo ligado a pigmentação; uso apenas sob orientação qualificada.",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "Bronzeamento",
    application: "Protocolo estético",
    limitedStock: false
  },
  {
    id: "gt-p019",
    name: "CJC-1295",
    dosage: "2mg",
    price: 294,
    description: "Análogo liberador de GH com perfil para pulsos e recuperação.",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "GH",
    application: "Stacks GH",
    limitedStock: false
  },
  {
    id: "gt-p020",
    name: "CJC-1295",
    dosage: "5mg",
    price: 348,
    description: "Dosagem intermediária para ciclos supervisionados.",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "GH",
    application: "Composição",
    limitedStock: false
  },
  {
    id: "gt-p021",
    name: "CJC-1295 DAC",
    dosage: "10mg",
    price: 348,
    description: "Variante com meia-vida estendida; protocolos com menos aplicações.",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "GH sustentado",
    application: "Ciclos longos",
    limitedStock: false
  },
  {
    id: "gt-p022",
    name: "CJC + IPAMORELIN",
    dosage: "—",
    price: 348,
    description: "Stack sinérgico para resposta de GH com curadoria técnica.",
    badge: "Blend",
    category: "Peptídeos",
    benefit: "GH combinado",
    application: "Blend premium",
    images: ["./assets/cjc-1295-ipamorelin-10mg.png"],
    limitedStock: true
  },
  {
    id: "gt-p023",
    name: "SEMAX",
    dosage: "5mg",
    price: 321,
    description: "Peptídeo nootrópico para cognição, foco e clareza mental.",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "Cognição",
    application: "Nootropia",
    limitedStock: false
  },
  {
    id: "gt-p024",
    name: "TB-500",
    dosage: "5mg",
    price: 241,
    description: "Thymosin beta-4 para mobilidade tecidual e recuperação.",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "Mobilidade",
    application: "Tendões / fáscias",
    limitedStock: false
  },
  {
    id: "gt-p025",
    name: "TB-500",
    dosage: "10mg",
    price: 348,
    description: "Maior concentração por frasco para protocolos intensivos.",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "Mobilidade",
    application: "Recuperação",
    limitedStock: false
  },
  {
    id: "gt-p026",
    name: "SS-31",
    dosage: "10mg",
    price: 407,
    description: "Peptídeo mitocondrial para energia celular e performance.",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "Mitocondrias",
    application: "Longevidade",
    limitedStock: false
  },
  {
    id: "gt-p027",
    name: "5-AMINO-1MQ",
    dosage: "5mg",
    price: 321,
    description: "Modulador metabólico para linha avançada de recomposição.",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "Metabolismo",
    application: "Cutting",
    limitedStock: false
  },
  {
    id: "gt-h001",
    name: "HCG",
    dosage: "5000 UI",
    price: 187,
    description: "Gonadotrofina coriônica humana; linha hormonal sob orientação qualificada.",
    badge: "Hormonal",
    category: "Hormônios & CIA",
    benefit: "Eixo hormonal",
    application: "Protocolo médico",
    limitedStock: false
  },
  {
    id: "gt-h002",
    name: "HCG",
    dosage: "10000 UI",
    price: 278,
    description: "Apresentação com maior potência unitária (UI) conforme lista oficial.",
    badge: "Hormonal",
    category: "Hormônios & CIA",
    benefit: "Eixo hormonal",
    application: "Protocolo médico",
    limitedStock: false
  },
  {
    id: "gt-h003",
    name: "HGH Fragment",
    dosage: "—",
    price: 642,
    description: "Fragmento da molécula de GH associado a lipólise e performance.",
    badge: "Hormonal",
    category: "Hormônios & CIA",
    benefit: "Lipólise / GH",
    application: "Hormonal avançado",
    limitedStock: false
  },
  {
    id: "gt-h004",
    name: "PT-141",
    dosage: "10mg",
    price: 303,
    description: "Peptídeo com indicações específicas; uso apenas com prescrição/orientação.",
    badge: "Hormonal",
    category: "Hormônios & CIA",
    benefit: "Protocolo específico",
    application: "Sob prescrição",
    images: ["./assets/pt-141-10mg.png"],
    limitedStock: false
  },
  {
    id: "gt-h005",
    name: "MOTS-C",
    dosage: "10mg",
    price: 326,
    description: "Peptídeo mitocondrial ligado a metabolismo e sensibilidade ao exercício.",
    badge: "Hormonal",
    category: "Hormônios & CIA",
    benefit: "Metabolismo",
    application: "Performance",
    limitedStock: false
  },
  {
    id: "gt-m001",
    name: "Água Bacteriostática",
    dosage: "10ml",
    price: 70,
    description: "Diluente estéril com conservante para reconstituição.",
    badge: "Medicamento",
    category: "Medicamentos",
    benefit: "Reconstituição",
    application: "Uso técnico",
    limitedStock: false
  },
  {
    id: "gt-m002",
    name: "Água Bacteriostática",
    dosage: "3ml",
    price: 28,
    description: "Ampola compacta para volumes menores.",
    badge: "Medicamento",
    category: "Medicamentos",
    benefit: "Reconstituição",
    application: "Frascos pequenos",
    limitedStock: false
  },
  {
    id: "gt-m003",
    name: "Água para Injeção",
    dosage: "3ml",
    price: 16,
    description: "WFI para diluição imediata sem conservante.",
    badge: "Medicamento",
    category: "Medicamentos",
    benefit: "Diluição",
    application: "Uso único",
    limitedStock: false
  },
  {
    id: "gt-p028",
    name: "Epithalon",
    dosage: "10mg",
    price: 0,
    description: "Peptídeo.",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "-",
    application: "-",
    images: ["./assets/epithalon-10mg.png"],
    limitedStock: false
  },
  {
    id: "gt-p029",
    name: "Retatrutide",
    dosage: "20mg",
    price: 0,
    description: "Peptídeo.",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "-",
    application: "-",
    images: ["./assets/retatrutide-20mg.png"],
    limitedStock: false
  },
  {
    id: "gt-p030",
    name: "Retatrutide",
    dosage: "40mg",
    price: 0,
    description: "Peptídeo.",
    badge: "Peptídeo",
    category: "Peptídeos",
    benefit: "-",
    application: "-",
    images: ["./assets/retatrutide-40mg.png"],
    limitedStock: false
  }
];
